graph TD
    test_method["test_method"]
    __init__["__init__"]
    test_subfunction["test_subfunction"]
    TestClass["TestClass"]
    TestClass -.-> test_subfunction
    test_method --> test_subfunction
    TestClass --> __init__
    TestClass --> test_method
    style TestClass fill:#bbf,stroke:#333,stroke-width:2px