vars: {
  d2-config: {
    sketch: true
  }
}
classes: {
  file: {
    label: ""
    shape: diamond
    style: {
      fill: yellow
      shadow: true
    }
  }
}

classes: {
  class: {
    label: ""
    shape: rectangle
    style: {
      fill: lightblue
      shadow: true
    }
  }
}

classes: {
  object: {
    label: ""
    shape: hexagon
    style: {
      fill: while
      shadow: false
    }
  }
}
entropix.main.main.class: file
entropix.main.main.label: "main"
entropix.main.main: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_main.torch_main.class: file
entropix.torch_main.torch_main.label: "torch_main"
entropix.torch_main.torch_main: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}