vars: {
  d2-config: {
    sketch: true
  }
}
classes: {
  file: {
    label: ""
    shape: diamond
    style: {
      fill: yellow
      shadow: true
    }
  }
}

classes: {
  class: {
    label: ""
    shape: hexagon
    style: {
      fill: lightblue
      shadow: true
    }
  }
}

classes: {
  function: {
    label: ""
    shape: rectangle
    style: {
      fill: white
      shadow: false
    }
  }
}
entropix.kvcache.update.class: function
entropix.kvcache.update.label: "update"
entropix.kvcache.update: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.kvcache.new.class: function
entropix.kvcache.new.label: "new"
entropix.kvcache.new: {
  style: {
    opacity: 0.50
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.kvcache.KVCache.class: class
entropix.kvcache.KVCache.label: "KVCache"
entropix.kvcache.KVCache: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.kvcache.kvcache.class: file
entropix.kvcache.kvcache.label: "kvcache"
entropix.kvcache.kvcache: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.kvcache.update -> entropix.kvcache.new: {
  style.stroke: black
  style.opacity: 0.50
  style.stroke-width: 2
}
entropix.kvcache.update -> entropix.kvcache.update: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
entropix.kvcache.update -> entropix.kvcache.KVCache: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
entropix.kvcache.KVCache -> entropix.kvcache.new: {
  style.stroke: black
  style.opacity: 0.50
  style.stroke-width: 2
}
entropix.kvcache.KVCache -> entropix.kvcache.update: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
entropix.kvcache.KVCache -> entropix.kvcache.KVCache: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
entropix.kvcache.kvcache -> entropix.kvcache.new: {
  style.stroke: red
  style.opacity: 0.50
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.kvcache.kvcache -> entropix.kvcache.KVCache: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.kvcache.kvcache -> entropix.kvcache.update: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}