vars: {
  d2-config: {
    sketch: true
  }
}
classes: {
  file: {
    label: ""
    shape: diamond
    style: {
      fill: yellow
      shadow: true
    }
  }
}

classes: {
  class: {
    label: ""
    shape: rectangle
    style: {
      fill: lightblue
      shadow: true
    }
  }
}

classes: {
  object: {
    label: ""
    shape: hexagon
    style: {
      fill: while
      shadow: false
    }
  }
}
_github.class: function
_github.label: "_github"
_github: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
_gitignore.class: file
_gitignore.label: "_gitignore"
_gitignore: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
_markdown-link-check_config_json.class: file
_markdown-link-check_config_json.label: "_markdown-link-check_config_json"
_markdown-link-check_config_json: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
CONTRIBUTING_md.class: file
CONTRIBUTING_md.label: "CONTRIBUTING_md"
CONTRIBUTING_md: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
LICENSE.class: file
LICENSE.label: "LICENSE"
LICENSE: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
Makefile.class: file
Makefile.label: "Makefile"
Makefile: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
README_md.class: file
README_md.label: "README_md"
README_md: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
docs.class: function
docs.label: "docs"
docs: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
examples.class: function
examples.label: "examples"
examples: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
libs.class: function
libs.label: "libs"
libs: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
poetry_lock.class: file
poetry_lock.label: "poetry_lock"
poetry_lock: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
pyproject_toml.class: file
pyproject_toml.label: "pyproject_toml"
pyproject_toml: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
security_md.class: file
security_md.label: "security_md"
security_md: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
ISSUE_TEMPLATE.class: function
ISSUE_TEMPLATE.label: "ISSUE_TEMPLATE"
ISSUE_TEMPLATE: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
actions.class: function
actions.label: "actions"
actions: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}